From 2d10c07e53ab993a8c447c691ffeaef5b92e1d60 Mon Sep 17 00:00:00 2001
From: nikosapi <me@nikosapi.org>
Date: Wed, 3 Jun 2009 13:32:15 -0400
Subject: [PATCH] Include a custom version of redirect_internal in DownloadURLOpener

This addresses bug #465
---
 src/gpodder/download.py |   22 +++++++++++++++++++++-
 1 files changed, 21 insertions(+), 1 deletions(-)

diff --git a/src/gpodder/download.py b/src/gpodder/download.py
index efe0413..ab51530 100644
--- a/src/gpodder/download.py
+++ b/src/gpodder/download.py
@@ -36,6 +36,7 @@ import gpodder
 
 import threading
 import urllib
+import urlparse
 import shutil
 import os.path
 import os
@@ -184,7 +185,26 @@ class DownloadURLOpener(urllib.FancyURLopener):
         void = fp.read()
         fp.close()
         raise gPodderDownloadHTTPError(url, errcode, errmsg)
-
+    
+    def redirect_internal(self, url, fp, errcode, errmsg, headers, data):
+        """ This is the exact same function that's included with urllib
+            except with "void = fp.read()" commented out. """
+        
+        if 'location' in headers:
+            newurl = headers['location']
+        elif 'uri' in headers:
+            newurl = headers['uri']
+        else:
+            return
+        
+        # This blocks forever(?) with certain servers (see bug #465)
+        #void = fp.read()
+        fp.close()
+        
+        # In case the server sent a relative URL, join with original:
+        newurl = urlparse.urljoin(self.type + ":" + url, newurl)
+        return self.open(newurl)
+    
 # The following is based on Python's urllib.py "URLopener.retrieve"
 # Also based on http://mail.python.org/pipermail/python-list/2001-October/110069.html
 
-- 
1.6.0.4

